
        window._currentDevice = 'desktop';
        window.Parameters = window.Parameters || {
            AjaxContainer: 'div.dmBody',
            WrappingContainer: 'div.dmOuter',
            HomeUrl: 'https://www.dettaglissima.net/',
            AccountUUID: '9b900da801ce4bf8a77455b58643b861',
            SystemID: 'US_DIRECT_PRODUCTION',
            SiteAlias: '40882f5e',
            SiteId: '2376250',
            SiteType: atob('RFVEQU9ORQ=='),
            PublicationDate: 'Tue Jan 25 09:32:48 UTC 2022',
            ExternalUid: null,
            IsSiteMultilingual: true,
            InitialPostAlias: '',
            InitialDynamicItem: '',
            InitialPageAlias: 'it',
            InitialPageUuid: '2c5e22a7bb5f482c999e280d6b326a0d',
            InitialEncodedPageAlias: 'aXQ=',
            CurrentPageUrl: '',
            IsCurrentHomePage: false,
            AllowAjax: false,
            AfterAjaxCommand: null,
            HomeLinkText: 'Back To Home',
            UseGalleryModule: false,
            CurrentThemeName: 'Layout Theme',
            ThemeVersion: '4645',
            DefaultPageAlias: '',
            RemoveDID: true,
            WidgetStyleID: null,
            IsHeaderFixed: false,
            IsHeaderSkinny: false,
            IsBfs: true,
            StorePageAlias: 'null',
            StorePagesUrls: 'e30=',
            IsNewStore: 'false',
            StorePath: '',
            StoreId: 'null',
            StoreVersion: 0,
            StoreBaseUrl: '',
            StoreCleanUrl: true,
            StoreDisableScrolling: true,
            NotificationSubDomain: 'dettaglissima',
            HasCustomDomain: true,
            showCookieNotification: true,
            cookiesNotificationMarkup: ' <div>Utilizziamo i cookie per garantire la miglior esperienza possibile sul nostro sito Web. Per maggiori informazioni, passare alla pagina della privacy.<\/div> \n',
            translatedPageUrl: '/it',
            isFastMigrationSite: false,
            sidebarPosition: 'NA',
            currentLanguage: 'it',
            NavItems: 'W3sidGl0bGUiOiJIb21lIiwiYWxpYXMiOiJpdCIsInBhdGgiOiIvaXQiLCJpbk5hdmlnYXRpb24iOnRydWUsInN1Yk5hdiI6W119LHsidGl0bGUiOiJDaGkgc2lhbW8iLCJhbGlhcyI6Iml0L2NoaS1zaWFtbyIsInBhdGgiOiIvaXQvY2hpLXNpYW1vIiwiaW5OYXZpZ2F0aW9uIjp0cnVlLCJzdWJOYXYiOltdfSx7InRpdGxlIjoiR2FsbGVyaWEiLCJhbGlhcyI6Iml0L2dhbGxlcmlhIiwicGF0aCI6Ii9pdC9nYWxsZXJpYSIsImluTmF2aWdhdGlvbiI6dHJ1ZSwic3ViTmF2IjpbXX0seyJ0aXRsZSI6IlByZXp6aSIsImFsaWFzIjoiaXQvcHJpY2luZyIsInBhdGgiOiIvaXQvcHJpY2luZyIsImluTmF2aWdhdGlvbiI6ZmFsc2UsInN1Yk5hdiI6W119LHsidGl0bGUiOiJDb250YXR0byIsImFsaWFzIjoiaXQvY29udGF0dGFjaSIsInBhdGgiOiIvaXQvY29udGF0dGFjaSIsImluTmF2aWdhdGlvbiI6dHJ1ZSwic3ViTmF2IjpbXX1d',
            errors: {
                general: 'Si è verificato un errore durante la connessione alla pagina.<br /> Assicurati di essere online.',
                password: 'Combinazione nome/password non corretta',
                tryAgain: 'Riprova'
            },
            NavigationAreaParams: {
                ShowBackToHomeOnInnerPages: true,
                NavbarSize: 4,
                NavbarLiveHomePage: 'https://www.dettaglissima.net/',
                BlockContainerSelector: '.dmBody',
                NavbarSelector: '#dmNav:has(a)',
                SubNavbarSelector: '#subnav_main'
            },
            hasCustomCode: false,
            planID: '1542',
            customTemplateId: 'null',
            siteTemplateId: 'null',
            productId: 'DM_DIRECT',
            disableTracking: false,
            pageType: 'FROM_SCRATCH',
            isRuntimeServer: true,
            siteCacheKey: '1643103194497_40882f5e',
            siteInfo: null,
        };
    
        window.Parameters.LayoutID = {};
        window.Parameters.LayoutID[window._currentDevice] = 6;
        window.Parameters.LayoutVariationID = {};
        window.Parameters.LayoutVariationID[window._currentDevice] = 5;
    